Release Notes for 10/08
Azure/AKS pull request #2592
Opened 2021-10-09 05:53 UTC by justindavies

2021-10-11 14:38 UTC, miwithro approved these changes

2021-10-13 08:15 UTC, PixelRobots requested changes

2021-10-13 08:15 UTC, PixelRobots commented on CHANGELOG.md
> +  * Public Preview of support for WASM/WASI based nodepools
worth adding the docs page https://docs.microsoft.com/en-us/azure/aks/use-wasi-node-pools

2021-10-13 08:15 UTC, PixelRobots commented on CHANGELOG.md
> +  * Public Preview of HTTP Proxy
Worth adding the docs page https://docs.microsoft.com/en-us/azure/aks/http-proxy

2021-10-13 08:15 UTC, PixelRobots commented on CHANGELOG.md
> +  * General Availability of Ultra SSD support
worth adding a link to the docs. https://docs.microsoft.com/en-us/azure/aks/use-ultra-disks

2021-10-14 14:16 UTC, merged