1-27-release-changes
Azure/AKS pull request #2761
Opened 2022-01-28 22:33 UTC by kaarthis

Please review 2022-1-27 release notes.

2022-01-28 22:53 UTC, phealy commented on CHANGELOG.md
> +  * For new, dual-stack clusters when --pod-cidrs or --service-cidrs are omitted, AKS will now create pseudo-random IPv6 address ranges for the Kubernetes pod and service IPs per    RFC 4193, instead
```suggestion
  * AKS will now create pseudo-random IPv6 address ranges for the Kubernetes pod and service IPs for new dual-stack clusters when --pod-cidrs or --service-cidrs are omitted instead of a default static value. These ranges will be generated with the method suggested in RFC 4193.
```

2022-01-29 00:16 UTC, palma21 requested changes

2022-01-29 00:16 UTC, palma21 commented on CHANGELOG.md
> +* Upgraded Linux version to 5.4.0-1067.70-azure to address CVE-2022-0185 (https://github.com/Azure/AKS/issues/2749.
Linked/sub bullet on the VHD Component update.

2022-01-29 00:16 UTC, palma21 commented on CHANGELOG.md
> +* Client automatic cert rotation is now being enabled on the last set of regions.
Already done.

2022-01-29 00:16 UTC, palma21 commented on CHANGELOG.md
> +  * CNI Plugins should now be toggle enabled and moved to version 0.9.1.
Already on last week's

2022-01-29 00:45 UTC, kaarthis reviewed
Please review and approve.

2022-02-02 19:44 UTC, justindavies approved these changes

2022-02-02 20:43 UTC, miwithro approved these changes

2022-02-03 01:01 UTC, kaarthis commented
#sign-off this one.

2022-02-03 01:03 UTC, palma21 commented on CHANGELOG.md
> +* Kubernetes 1.19 will be removed on 2022-01-31.
Will be removed on the next release.

2022-02-03 01:15 UTC, kaarthis commented on CHANGELOG.md
> +* Kubernetes 1.19 will be removed on 2022-01-31.
Done

2022-02-03 01:15 UTC, kaarthis commented
Please approve 2-2-2022

2022-02-03 01:20 UTC, palma21 approved these changes

2022-02-03 01:39 UTC, merged