Release Notes for 2022-02-01
Azure/AKS pull request #2773
Opened 2022-02-07 18:12 UTC by justindavies

2022-02-08 17:31 UTC, qpetraroia approved these changes

2022-02-08 17:43 UTC, kaarthis commented on CHANGELOG.md
> +* Starting with 1.23 AKS will follow upstream kubernetes and deprecate in-tree azure authentication which is marked for deprecation to be replaced with 'exec'. If you are using Azure CLI or Azure cli
This is a [client-go credential (exec) plugin](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins) implementing azure authentication. This plugin provides features that are not available in kubectl. It is supported on kubectl v1.11+ - Think if we explain the exec plugin with a link it ll be much easier for ppl like me first knowing about this!

2022-02-08 18:31 UTC, palma21 requested changes

2022-02-08 18:31 UTC, palma21 commented on CHANGELOG.md
> +  * Enable ephemeral OS on [temp disk](https://aka.ms/aks/ephemeral-os-temp)
Do we have a doc update lined up on the AKS Ephemeral OS docs?
https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#ephemeral-os

We're still calling out the requirement for cache size.

2022-02-08 18:31 UTC, palma21 commented on CHANGELOG.md
> +    * Kubernetes 1.20.15, 1.21.9 and 1.22.6 released, 1.20.9, 1.21.2, and 1.22.2 removed
1.19 removed?

2022-02-08 18:31 UTC, palma21 commented on CHANGELOG.md
> +* Kubernetes 1.19 will be removed on the next release.
Can remove?

2022-02-08 18:33 UTC, justindavies commented on CHANGELOG.md
> +* Kubernetes 1.19 will be removed on the next release.
Deprecation is still WIP

2022-02-08 19:07 UTC, justindavies commented on CHANGELOG.md
> +    * Kubernetes 1.20.15, 1.21.9 and 1.22.6 released, 1.20.9, 1.21.2, and 1.22.2 removed
WIP

2022-02-08 22:16 UTC, miwithro requested changes

2022-02-08 22:16 UTC, miwithro commented on CHANGELOG.md
> +    * Kubernetes 1.20.15, 1.21.9 and 1.22.6 released, 1.20.9, 1.21.2, and 1.22.2 removed
```suggestion
    * Kubernetes 1.20.15, 1.21.9 and 1.22.6 released, 1.20.9, 1.21.2, and 1.22.2 removed
    * Upgraded Linux version to 5.4.0-1068.70-azure to address [CVE-2021-4034](https://github.com/Azure/AKS/issues/2756 )
    * Containerd registry configuration for Linux nodes - including adding root CAs for containerd via DS.
```

2022-02-09 16:39 UTC, miwithro approved these changes

2022-02-09 17:19 UTC, merged