release notes March 237 - April 3
Azure/AKS pull request #2890
Opened 2022-04-08 06:39 UTC by qpetraroia

2022-04-08 11:40 UTC, PixelRobots commented on CHANGELOG.md
> +  * Windows Server 2022 is now available to use as your AKS cluster windows node when you enable `aks-preview` and register feature `Microsoft.ContainerService/AKSWindows2022Preview` and set `--os-sk
Would be good for a blog post here and also to include the vhd-notes

2022-04-08 15:15 UTC, palma21 requested changes

2022-04-08 15:15 UTC, palma21 commented on CHANGELOG.md
> +  * Azure Keyvault Secrets Provider has been updated to v1.1.0.
Link release notes pls

2022-04-08 15:15 UTC, palma21 commented on CHANGELOG.md
> +  * Azure Disk CSI driver has been updated to 1.14.
Link rel notes pls

2022-04-08 15:15 UTC, palma21 commented on CHANGELOG.md
> +  * Azure File CSI driver has been updated to 1.13.
Link rel notes please

2022-04-08 17:22 UTC, miwithro reviewed
@qpetraroia we pull the first announcement around the Upgrade for the security patches.

2022-04-08 17:48 UTC, miwithro approved these changes

2022-04-08 20:39 UTC, palma21 commented on CHANGELOG.md
> +* Node Pool Snapshot CLI experience is changing by April 6,  2022. The current nodepool snapshot commands i.e az `aks snapshot` will now be `az aks nodepool snapshot`.
This is now in the past.

2022-04-09 00:16 UTC, palma21 approved these changes

2022-04-09 00:24 UTC, merged