2022-07-31 release notes
Azure/AKS pull request #3116
Opened 2022-08-03 22:33 UTC by justindavies

2022-08-04 16:22 UTC, olsenme commented
lgtm

2022-08-04 17:51 UTC, miwithro requested changes
KMS is also GA!!

2022-08-05 19:06 UTC, palma21 commented on CHANGELOG.md
> +* Bug Fixes
Extra line

2022-08-05 19:07 UTC, palma21 commented on CHANGELOG.md
> +  * [Confidential Virtual Machines](https://docs.microsoft.com/en-us/azure/aks/use-cvm) is now in Public Preview.
Missing KMS

2022-08-05 22:12 UTC, palma21 approved these changes

2022-08-05 22:12 UTC, merged