Update codespell.yml
Azure/AKS pull request #3277
Opened 2022-10-18 16:43 UTC by miwithro

2022-10-18 19:26 UTC, qpetraroia commented
@andyzhangx is this correct?

2022-10-18 19:26 UTC, qpetraroia approved these changes

2022-10-18 19:48 UTC, shashankbarsin requested changes

2022-10-18 19:48 UTC, shashankbarsin commented on .github/workflows/codespell.yml
> +          skip: ./.git,./.github/workflows/codespell.yml,.git,*.png,*.jpg,*.svg,*.sum, /.vhd-notes/*
```suggestion
          skip: ./.git,./.github/workflows/codespell.yml,.git,*.png,*.jpg,*.svg,*.sum,./vhd-notes/*
```

2022-10-18 19:50 UTC, shashankbarsin approved these changes

2022-10-18 19:51 UTC, miwithro commented
#sign-off

2022-10-18 19:51 UTC, merged

2022-10-19 02:16 UTC, andyzhangx commented
@qpetraroia if you could make codespell test pass, then that's correct