2023-1-28 add WI label
Azure/AKS pull request #3442
Opened 2023-01-28 12:07 UTC by CocoWang-wql

2023-01-28 13:26 UTC, miwithro approved these changes

2023-01-29 04:53 UTC, lilyandcy requested changes
Please include label change only in the latest release note(2023-01-22). Leave older release notes no change to keep consistency.

2023-01-29 05:12 UTC, lilyandcy approved these changes
Looks good after resolving previous comments.

2023-01-29 05:16 UTC, merged

2023-02-01 00:05 UTC, miwithro commented
#sign-off