release notes for March 12th 2023
Azure/AKS pull request #3562
Opened 2023-03-24 16:24 UTC by allyford

2023-03-24 16:34 UTC, wangyira requested changes

2023-03-24 16:34 UTC, wangyira commented on CHANGELOG.md
> +  * To enable InifinBand, set SPG and PlatformDomainCount. This setting is invalid and cannot be enabled for node pools with multile zones.
small spelling issue: "multiple"

2023-03-24 16:41 UTC, kaarthis commented on CHANGELOG.md
> +  * Fixed an issue where default Linux sysctls were not applied if users specified any Linux OS config. If these sysctls were not specified, the defaults may previously have changed unintentionally:
Looks pretty technical and since there are multiple sysctls any doc link to elaborate may help here ?

2023-03-24 18:54 UTC, kaarthis approved these changes

2023-03-24 21:08 UTC, allyford commented on CHANGELOG.md
> +  * Podsubnet won't work in ussec/usnat. Mooncake and fairfax regions will not be affected.
removed

2023-03-29 02:38 UTC, justindavies approved these changes

2023-03-29 14:43 UTC, phealy requested changes
See feedback.

2023-03-29 14:43 UTC, phealy commented on CHANGELOG.md
> +* Docker container runtime will be retired for Windows nodepools on May 1, 2023. After docker container runtime is retired, you may remain on existing deployed instances but scaling operations will f
```suggestion
* Docker container runtime will be retired for Windows nodepools on May 1, 2023. After docker container runtime is retired, you may remain on existing deployed instances but scaling operations will fail, nodepool creation will fail, and you will be out of support. Follow the detailed steps [in our documentation](https://learn.microsoft.com/azure/aks/learn/quick-windows-container-deploy-cli) to upgrade to containerd.
```

Please remove language tags from documentation links.

2023-03-29 14:43 UTC, phealy commented on CHANGELOG.md
> +  * CNI Overlay uses hostProcess containers on Windows node pools (CNS) which is not compatible with nodes using docker as the container runtime. Clusters that may be upgrading from CNI v1 using dock
```suggestion
```

Overlay upgrade functionality is not yet available, no need to announce this.

2023-03-29 16:22 UTC, phealy approved these changes

2023-03-29 16:50 UTC, merged