0507 rel notes
Azure/AKS pull request #3640
Opened 2023-05-05 21:19 UTC by kaarthis

Please review team.

2023-05-05 21:39 UTC, shashankbarsin commented on CHANGELOG.md
> +   * Upgraded blob csi driver to [v1.19.5](https://github.com/kubernetes-sigs/blob-csi-driver/releases/tag/v1.19.5) on AKS 1.24, 1.25 to fix blobfuse install failures.
this should be under component updates section

2023-05-05 21:45 UTC, shashankbarsin commented on CHANGELOG.md
> +   * Now returning a clientError, when you do Stop/RunCommand action on a cluster that was never successfully provisioned and was stuck in failed state.
do we have the exact error message?

2023-05-05 21:47 UTC, shashankbarsin commented on CHANGELOG.md
> +   * The Docker Bridge CIDR field in the AKS API was made redundant during our change from Docker to containerD in Kubernetes version 1.19. Starting with the 2023-04-01 AKS API version, the Docker Br
should this be under announcements?

2023-05-05 21:51 UTC, kaarthis commented on CHANGELOG.md
> +   * The Docker Bridge CIDR field in the AKS API was made redundant during our change from Docker to containerD in Kubernetes version 1.19. Starting with the 2023-04-01 AKS API version, the Docker Br
Good point.

2023-05-07 02:01 UTC, shashankbarsin commented on CHANGELOG.md
> +  * Azure Service Mesh add-on's Istiod and ingress images updated from v1.17.1 to [v1.17.2 patch](https://github.com/istio/istio/compare/1.17.1...1.17.2).
```suggestion
  * Istio-based service mesh add-on's istiod and ingress images updated from v1.17.1 to v1.17.2. User needs to restart the workload pods to trigger re-injection of the newer patch version of istio-proxy. More information can be found [here](https://learn.microsoft.com/azure/aks/istio-upgrade).
```

2023-05-07 02:04 UTC, shashankbarsin commented on CHANGELOG.md
> +* Starting on March 21, 2023, traffic to k8s.gcr.io will be redirected to registry.k8s.io, following the [community announcement](https://kubernetes.io/blog/2023/03/10/image-registry-redirect/).
We can remove this line. It's now more than a month

2023-05-07 02:05 UTC, shashankbarsin commented on CHANGELOG.md
> +  * AKS updated the OSM addon on clusters running AKS k8s version >= v1.24.0 from OSM v1.2.3 to v.1.2.4. Details [here](https://github.com/openservicemesh/osm/releases/tag/v1.2.4).
```suggestion
  * Open Service Mesh add-on images updated from v1.2.3 to [v1.2.4](https://github.com/openservicemesh/osm/releases/tag/v1.2.4) for AKS clusters of version >= 1.24.0.
```

2023-05-07 02:08 UTC, shashankbarsin commented on CHANGELOG.md
> +  * Upgraded Cilium to version 1.12.8 along with changes to match [upstream](https://github.com/cilium/cilium/pull/24075/files#diff-8d03af2c9f8f368b86831ae81cfb6f4152e884baf74366c09f2d92363ad791e7).
```suggestion
  * Cilium upgraded to [1.12.8](https://github.com/cilium/cilium/releases/tag/v1.12.8) for [AKS clusters with Azure CNI Powered by Cilium](https://learn.microsoft.com/en-us/azure/aks/azure-cni-powered-by-cilium).
```

2023-05-08 20:57 UTC, qpetraroia commented
Signing off given that @shashankbarsin's suggestions are committed

2023-05-08 20:57 UTC, qpetraroia approved these changes

2023-05-08 20:58 UTC, qpetraroia approved these changes

2023-05-08 21:30 UTC, shashankbarsin commented on CHANGELOG.md
>     * Added update permission for ciliumidentity, without this permission- cilium-operator and ciliumAgent cannot garbage collect unused [identities](https://github.com/cilium/cilium/commit/2adf5f4313
Updated 'cilium', 'cilium-operator', 'cilium-pre-flight' ClusterRoles to include 'update' permission for 'ciliumidentities' api-resource. This addresses the issue where cilium-operator and cilium-agent couldn't garbage collect unused identities.

2023-05-08 21:30 UTC, shashankbarsin commented on CHANGELOG.md
> +   * Csi-provisioner version updated to v3.5.0 in order to fix a volume deletion issue, [details](https://github.com/kubernetes/kubernetes/issues/100485#issuecomment-1497878875)
this is component version bump. we need to move it there

2023-05-08 21:31 UTC, shashankbarsin commented on CHANGELOG.md
> +   * The CPU limit of Azure Monitor Metrics Addon (Windows Daemonset) is updated from 200m to 500m to fix a throttling issue.
The CPU limit Windows DaemonSet ofAzure Monitor Metrics Addon is updated from 200m to 500m to fix throttling issue.

2023-05-08 21:32 UTC, shashankbarsin commented on CHANGELOG.md
>  * Docker container runtime will be retired for Windows nodepools on May 1, 2023. After docker container runtime is retired, you may remain on existing deployed instances but scaling operations will f
nit for tense: "Docker container runtime will be retired for Windows nodepools on May 1, 2023" -> "Docker container runtime has been retired for Windows nodepools on May 1, 2023"

2023-05-09 04:44 UTC, palma21 requested changes

2023-05-09 04:44 UTC, palma21 commented on CHANGELOG.md
> +  * Validations logic added to error out in [Azure CNI overlay](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/insufficientsubnetsize-error-advanced-networking) clusters, whene
Why is the validation a component update and not a bug fix or behavioral change?

2023-05-09 04:44 UTC, palma21 commented on CHANGELOG.md
> +  * Validations logic added to error out in [Azure CNI overlay](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/insufficientsubnetsize-error-advanced-networking) clusters, whene
> whenever autoscaler max count or manual scale node count likely goes over the IP limits of what the managed subnet and podcidr settings get by default

also what does this mean? What happened before that now doesn't happen or vice versa?

2023-05-09 04:45 UTC, palma21 requested changes

2023-05-09 04:45 UTC, palma21 commented on CHANGELOG.md
Where's the VHDs?

2023-05-09 16:05 UTC, kaarthis commented
https://github.com/Azure/AgentBaker/tree/master/vhdbuilder/release-notes no new VHDs yet. lets go ahead and publish first.

2023-05-09 17:12 UTC, miwithro approved these changes

2023-05-09 23:47 UTC, shashankbarsin approved these changes

2023-05-10 00:41 UTC, kaarthis commented
@palma21 pls approve and so we can merge it.

2023-05-10 04:27 UTC, palma21 approved these changes

2023-05-10 15:57 UTC, merged