Release notes oct8 october15 2023
Azure/AKS pull request #3953
Opened 2023-10-17 04:56 UTC by kevinkrp93

2023-10-17 08:31 UTC, PixelRobots commented on CHANGELOG.md
> +  * Fis for PUT on ManagedCluster allowing more than the [maximum tag limit](https://learn.microsoft.com/en-us/Azure/azure-resource-manager/management/tag-resources#limitations) of 50 in some rare ca
Fis should be Fix

2023-10-17 13:37 UTC, AllenWen-at-Azure commented on CHANGELOG.md
> +  * Fix for preventing [cilium-operator](https://learn.microsoft.com/en-us/azure/aks/azure-cni-powered-by-cilium)  from restarting unmanaged coredns pods
According to the doc best practice, better to remove locale "en-us" from the URL, also apply to other doc linkage.

2023-10-17 13:44 UTC, AllenWen-at-Azure commented on CHANGELOG.md
> +  * Disable creation of new nodepools with OSSKU cblmariner as CBL-Mariner 1.0 is end of life
What is the suggested action to customers who are using cblmariner as os-sku right now? Is it "AzureLinux"?

2023-10-17 15:56 UTC, kevinkrp93 commented on CHANGELOG.md
> +  * Disable creation of new nodepools with OSSKU cblmariner as CBL-Mariner 1.0 is end of life
There are currently no existing doc for Mariner 1.0 (it was never advertised). There are 2 customers using a very small amount of it so adding it in a doc might cause confusion. PM suggested a release notes announcement should be fine or we can take it out entirely.

2023-10-18 14:15 UTC, miwithro commented on CHANGELOG.md
> +  * Fix for - [CVE-2023-44487](https://www.cve.org/CVERecord?id=CVE-2023-44487) - The HTTP/2 protocol allows a denial of service (server resource consumption) because request cancellation can reset m
@kevinkrp93 CVE-2023-44487 should point to https://github.com/Azure/AKS/issues/3947

2023-10-19 05:45 UTC, charleswool commented on CHANGELOG.md
> +
Feature release:

Image Integrity (https://learn.microsoft.com/en-us/azure/aks/image-integrity?tabs=azure-cli) is now Public Preview

2023-10-19 11:44 UTC, miwithro commented on CHANGELOG.md
> +
[CVE-2023-29332](https://github.com/Azure/AKS/issues/3904) Please update your AKS VHD to at least VHD version 230801 as mentioned in the issue.

2023-10-19 21:34 UTC, miwithro commented on CHANGELOG.md
> +  * [CVE-2023-29332](https://github.com/Azure/AKS/issues/3904) Please update your AKS VHD to at least VHD version 230801 as mentioned in the issue
Please move the CVE announcement from Component updates to Announcements as this CVE is alot more than just a VHD update.

2023-10-19 22:42 UTC, miwithro approved these changes

2023-10-20 01:23 UTC, justindavies approved these changes

2023-10-20 01:35 UTC, palma21 requested changes

2023-10-20 01:35 UTC, palma21 commented on CHANGELOG.md
> +  * Disable creation of new nodepools with OSSKU cblmariner as CBL-Mariner 1.0 is end of life
Internal only

2023-10-20 01:37 UTC, palma21 requested changes

2023-10-20 01:37 UTC, palma21 commented on CHANGELOG.md
> +* Feature
Missing above callout and the ones carried over from last week on probes, that now are out in docs.

@AllenWen-at-Azure @chasewilson

2023-10-20 03:08 UTC, AllenWen-at-Azure commented on CHANGELOG.md
> +* Feature
Kevin added this item below, might to refine it from "Customize the load balancer health probe." to "AKS supports to use annotations to configure the load balancer health probe for different service ports." @chasewilson @palma21 thoughts?

2023-10-20 18:45 UTC, shashankbarsin commented on CHANGELOG.md
> +* [CVE-2023-29332](https://github.com/Azure/AKS/issues/3904) Please update your AKS VHD to at least VHD version 230801 as mentioned in the issue
I think we should give a brief one line description of what's the vulnerability and what's at risk and then have this call out for them to update.

2023-10-20 18:46 UTC, shashankbarsin commented on CHANGELOG.md
> +  * AKS supports to use annotations to configure the [load balancer health probe](https://learn.microsoft.com/en-us/azure/aks/load-balancer-standard#customize-the-load-balancer-health-probe) for diff
need to remove 'en-us'

2023-10-20 18:47 UTC, shashankbarsin commented on CHANGELOG.md
> +  * Change error codes KeyVaultEncryptKeyFailed to KeyVaultEncryptFailed and KeyVaultDecryptKeyFailed to KeyVaultDecryptFailed
Error codes for which API or profile?

2023-10-20 19:55 UTC, PixelRobots commented on CHANGELOG.md
> +* [CVE-2023-29332](https://github.com/Azure/AKS/issues/3904) Microsoft Azure Kubernetes Service Elevation of Privilege Vulnerability. An attacker who successfully exploited this vulnerability could g
It might be wise to change AKS VHD to node image to match naming conventions with commands and the portal.

2023-10-20 21:01 UTC, palma21 approved these changes

2023-10-20 21:03 UTC, palma21 commented on CHANGELOG.md
> +  * AKS Ubuntu 18.04 image has been updated to [AKSUbuntu-1804-202310.09.0](vhd-notes/aks-ubuntu/AKSUbuntu-1804/202310.09.0.txt)
1804 is removed, you can remove this.

2023-10-20 21:20 UTC, merged