release-notes-2024-01-14
Azure/AKS pull request #4066
Opened 2024-01-16 17:22 UTC by allyford

2024-01-16 17:30 UTC, miwithro approved these changes

2024-01-16 17:30 UTC, kaarthis reviewed
PTAL

2024-01-16 17:30 UTC, kaarthis commented on CHANGELOG.md
> +* Kubernetes 1.25 has now deprecated and transitioned to [platform support](https://learn.microsoft.com/azure/aks/supported-kubernetes-versions?tabs=azure-cli#platform-support-policy). Please upgrade
been*

2024-01-16 17:30 UTC, kaarthis commented on CHANGELOG.md
> +* Kubernetes 1.25 has now deprecated and transitioned to [platform support](https://learn.microsoft.com/azure/aks/supported-kubernetes-versions?tabs=azure-cli#platform-support-policy). Please upgrade
or 'is now deprecated'

2024-01-16 17:30 UTC, kaarthis commented on CHANGELOG.md
> +  * Updated Retina Windows crash for k8s 1.28 with containerd 1.7. Containerd 1.7 causes Retina Windows to error with "setkubeconfigpath.ps1 and controller.exe not found on k8s version 1.28". This fi
We start with the error first like Containerd caused Retina windows to error with ....  This has now been fixed by updating the containerD 1.7 and applies to 1.28 version and above.

2024-01-16 17:30 UTC, kaarthis commented on CHANGELOG.md
> +  * Fixed missing api-group causing error in the rbac role for AGIC add-on: failed to list *v1beta1.AzureApplicationGatewayRewrite: azureapplicationgatewayrewrites.appgw.ingress.azure.io is forbidden
causing the following error

2024-01-16 17:30 UTC, kaarthis commented on CHANGELOG.md
> +  * AKS will no longer allow put/delete for privateEndpointConnection when the cluster is being updated.
Public doc ? GH?

2024-01-16 17:30 UTC, kaarthis commented on CHANGELOG.md
> +  * AKS will begin rejecting unknown fields starting in the 2024-01-01 API. Previously, unknown fields would have been ignored.
Public doc?

2024-01-16 23:27 UTC, wangyira requested changes

2024-01-16 23:27 UTC, wangyira commented on CHANGELOG.md
> +* Due to Gatekeeper Upstream removing validation for constraint template contents at create/update time, [the Azure Policy Add-On](https://learn.microsoft.com/azure/governance/policy/concepts/policy-
update the first link to https://learn.microsoft.com/azure/governance/policy/concepts/policy-for-kubernetes#install-azure-policy-add-on-for-aks

2024-01-16 23:27 UTC, wangyira commented on CHANGELOG.md
> +  * Updated minimum static [cpu limit](https://learn.microsoft.com/azure/aks/developer-best-practices-resource-management#:~:text=Pod%20CPU/Memory%20limits). Previously the minimum limit was set to t
what is the minimum set to now instead?

2024-01-16 23:40 UTC, stl327 commented on CHANGELOG.md
> +  * Changes to reduce the kube-reserved memory reservation and eviction threshold are now release with kubernetes v1.29. See changes to the kubelet daemon and memory reservations [here](https://learn
are now releasing with

2024-01-16 23:41 UTC, stl327 commented on CHANGELOG.md
> +  * Upgrade vpa recommender to v0.12.0 [v0.12.0](https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.12.0) and enable memory saver on production.
Upgraded vpa recommender
enabled memory saver

2024-01-17 00:49 UTC, charleswool commented on CHANGELOG.md
> +  * Updated max api server cpu limit to 15.
Is there a doc for the api server cpu limit for reference here similar to the above

2024-01-17 00:53 UTC, charleswool commented on CHANGELOG.md
> +  * Updated max api server cpu limit to 15.
Is there a doc for the api server cpu limit for reference here similar to the above+What's the previous limit?

2024-01-17 19:20 UTC, sabbour commented on CHANGELOG.md
> +  * App Routing version bump to [0.2.0](https://github.com/Azure/aks-app-routing-operator/blob/main/CHANGELOG.md). This includes a number of improvements including better logging, improvements to man
Link to doc (will be public when this is released): https://learn.microsoft.com/en-us/azure/aks/app-routing-nginx-configuration

2024-06-20 17:10 UTC, closed without merging